baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Jane Doe"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
title = "Chin Ming Jun"
author = "Chin Ming Jun"
description = "Thoughts and Deep Dives"
copyright = "2021-{{ YEAR }}"
doNotLoadAnimations = true
contentRatio = 0.8
fullPostContent = true
readMore = true

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://my.linkedin.com/in/chin-ming-jun"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/mjchi7"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mjchi7.misc@gmail.com"